<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Vusic_Player</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
	  <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="FFmpeg\avcodec-62.dll" />
    <None Remove="FFmpeg\avdevice-62.dll" />
    <None Remove="FFmpeg\avfilter-11.dll" />
    <None Remove="FFmpeg\avformat-62.dll" />
    <None Remove="FFmpeg\avutil-60.dll" />
    <None Remove="FFmpeg\ffmpeg.exe" />
    <None Remove="FFmpeg\ffplay.exe" />
    <None Remove="FFmpeg\ffprobe.exe" />
    <None Remove="FFmpeg\swresample-6.dll" />
    <None Remove="FFmpeg\swscale-9.dll" />
    <None Remove="Pages\MainPage.xaml" />
    <None Remove="Pages\VideoPlayer.xaml" />
    <None Remove="Pages\Views\AlbumView.xaml" />
    <None Remove="Pages\Views\ArtistView.xaml" />
    <None Remove="Pages\Views\EntireMusicLibrary.xaml" />
    <None Remove="Pages\Views\FolderView.xaml" />
    <None Remove="Pages\Views\HomeView.xaml" />
    <None Remove="Pages\Views\LoggerPage.xaml" />
    <None Remove="Pages\Views\LyricViewer.xaml" />
    <None Remove="Pages\Views\MusicLibrary.xaml" />
    <None Remove="Pages\Views\MusicPlayerFull.xaml" />
    <None Remove="Pages\Views\NoSearchResultsPage.xaml" />
    <None Remove="Pages\Views\PlaylistView.xaml" />
    <None Remove="Pages\Views\QueuePage.xaml" />
    <None Remove="Pages\Views\SearchResults.xaml" />
    <None Remove="Pages\Views\SettingsPage.xaml" />
    <None Remove="Pages\Views\ShowModel.xaml" />
    <None Remove="Pages\Views\VideoLibrary.xaml" />
    <None Remove="UI\Dialogs\OceanDialogConfig\OceanDialogWindow.xaml" />
    <None Remove="UI\Dialogs\OceanDialogConfig\OceanPopup.xaml" />
    <None Remove="UI\Dialogs\VideoOptionsWindow.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioAdvanced\AudioReverb.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioEqualizer\Equalizer.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Delay.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Device.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioGeneral\General.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Pitch.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Volume.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\PlayerSettingsHost.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Subtitle\SubtitleCustomize\Customize.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\Delay.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\General.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\SubtitleOnlineSearch.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoAspectRatio\AspectRatio.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoAspectRatio\AspectRatioCustom.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoFilters\Filters.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoGeneral\PlaybackSpeed.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoGeneral\Record.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoGeneral\Snapshot.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoGeneral\VideoStream.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoGeneral\View.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoOrientation\Flip.xaml" />
    <None Remove="UI\Dialogs\VideoOptions\VideoOrientation\Rotation.xaml" />
    <None Remove="UI\UserViews\Controls\GridViewRecentMusic.xaml" />
    <None Remove="UI\UserViews\Controls\ListViewMedia.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\AlbumEditor.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\InfoBox.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\MassEditor.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\MessagePanel.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\NewPlaylistCreation.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\OnlineArtistPicture.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\OnlineLyrics.xaml" />
    <None Remove="UI\UserViews\Controls\OceanDialogControls\ShowModelCreation.xaml" />
    <None Remove="UI\UserViews\Controls\OceanSlider.xaml" />
    <None Remove="UI\UserViews\Controls\PanelControlsAudioPlayer.xaml" />
    <None Remove="UI\UserViews\Controls\PlaybackMainControls.xaml" />
    <None Remove="UI\UserViews\Controls\PlayPauseControls.xaml" />
    <None Remove="UI\UserViews\Controls\SearchControl.xaml" />
    <None Remove="UI\UserViews\Controls\VideoControls.xaml" />
    <None Remove="UI\UserViews\Controls\VideoLibraryControls\RecommendedVideos.xaml" />
    <None Remove="UI\UserViews\Controls\VideoLibraryControls\UserShows.xaml" />
    <None Remove="UI\UserViews\Controls\VolumeSlider.xaml" />
    <None Remove="UI\UserViews\Grids\ContinuePlayingRecentsVideo.xaml" />
    <None Remove="UI\UserViews\Grids\DiveInGenres.xaml" />
    <None Remove="UI\UserViews\Grids\Favourites.xaml" />
    <None Remove="UI\UserViews\Grids\InstantPlaylists.xaml" />
    <None Remove="UI\UserViews\Grids\MusicListHome.xaml" />
    <None Remove="UI\UserViews\Grids\RecentMusicList.xaml" />
    <None Remove="UI\UserViews\Grids\TopTracks.xaml" />
    <None Remove="UI\UserViews\Grids\UserPlaylists.xaml" />
    <None Remove="UI\UserViews\PictureInPicture.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="FFmpeg\avcodec-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\avdevice-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\avfilter-11.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\avformat-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\avutil-60.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\ffplay.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\swresample-6.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FFmpeg\swscale-9.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Animations" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Collections" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
    <PackageReference Include="Flyleaf.FFmpeg.Bindings" Version="8.1.0" />
    <PackageReference Include="FlyleafLib.Controls.WinUI" Version="1.3.3" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Tes\Flyleaf\FlyleafLib\FlyleafLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Assets\audiofile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\LyricViewer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\OnlineLyrics.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\PictureInPicture.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\SearchControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\SubtitleOnlineSearch.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\Delay.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Volume.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Device.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Delay.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioGeneral\Pitch.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoAspectRatio\AspectRatioCustom.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoOrientation\Flip.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoGeneral\View.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoGeneral\VideoStream.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoGeneral\Snapshot.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoGeneral\Record.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\MusicPlayerFull.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\FolderView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\NoSearchResultsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\AlbumView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\ArtistView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\VideoPlayer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\PlaylistView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\TopTracks.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\DiveInGenres.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\InstantPlaylists.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\UserPlaylists.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\GridViewRecentMusic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\ShowModel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\ListViewMedia.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\ShowModelCreation.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\MassEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\AlbumEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\MessagePanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\OnlineArtistPicture.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\InfoBox.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanDialogControls\NewPlaylistCreation.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\OceanDialogConfig\OceanDialogWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\OceanDialogConfig\OceanPopup.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\VideoLibraryControls\RecommendedVideos.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\VideoLibraryControls\UserShows.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\Favourites.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\MusicListHome.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\RecentMusicList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Grids\ContinuePlayingRecentsVideo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\PanelControlsAudioPlayer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\VolumeSlider.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\SearchResults.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\LoggerPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\SettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\QueuePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\EntireMusicLibrary.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\VideoLibrary.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\MusicLibrary.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\Views\HomeView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\PlayPauseControls.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptionsWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\VideoControls.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\OceanSlider.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\UserViews\Controls\PlaybackMainControls.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\PlayerSettingsHost.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoGeneral\PlaybackSpeed.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoFilters\Filters.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoOrientation\Rotation.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\VideoAspectRatio\AspectRatio.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioGeneral\General.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioEqualizer\Equalizer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Audio\AudioAdvanced\AudioReverb.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Subtitle\SubtitleGeneral\General.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UI\Dialogs\VideoOptions\Subtitle\SubtitleCustomize\Customize.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
    <TrimMode>None</TrimMode>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <PackageCertificateKeyFile>Vusic Player_TemporaryKey.pfx</PackageCertificateKeyFile>
	  
  </PropertyGroup>
</Project>